### ISSUE TITLE
Fix warnings

### ISSUE THREAD

**Issue by iadnan** [HussainShabbir/Roman-numerals-Converter-in-Swift#1]
Fix warnings

**Comment by iadnan** [comment]
/Users/ibrahimadnan/Downloads/Roman-numerals-Converter-in-Swift-master/RomanNumeralsMapping/RomanNumeralsMapping/RnmCustomInputTableViewCell.swift:32:69: '++' is deprecated: it will be removed in Swift 3
/Users/ibrahimadnan/Downloads/Roman-numerals-Converter-in-Swift-master/RomanNumeralsMapping/RomanNumeralsMapping/RnmCustomInputTableViewCell.swift:32:9: C-style for statement is deprecated and will be removed in a future version of Swift
/Users/ibrahimadnan/Downloads/Roman-numerals-Converter-in-Swift-master/RomanNumeralsMapping/RomanNumeralsMapping/RnmCustomInputTableViewCell.swift:85:44: '++' is deprecated: it will be removed in Swift 3
/Users/ibrahimadnan/Downloads/Roman-numerals-Converter-in-Swift-master/RomanNumeralsMapping/RomanNumeralsMapping/RnmCustomInputTableViewCell.swift:85:13: C-style for statement is deprecated and will be removed in a future version of Swift
/Users/ibrahimadnan/Downloads/Roman-numerals-Converter-in-Swift-master/RomanNumeralsMapping/RomanNumeralsMapping/RnmCustomInputTableViewCell.swift:131:48: '++' is deprecated: it will be removed in Swift 3
/Users/ibrahimadnan/Downloads/Roman-numerals-Converter-in-Swift-master/RomanNumeralsMapping/RomanNumeralsMapping/RnmCustomInputTableViewCell.swift:135:37: '++' is deprecated: it will be removed in Swift 3
/Users/ibrahimadnan/Downloads/Roman-numerals-Converter-in-Swift-master/RomanNumeralsMapping/RomanNumeralsMapping/RnmCustomInputTableViewCell.swift:131:17: C-style for statement is deprecated and will be removed in a future version of Swift
/Users/ibrahimadnan/Downloads/Roman-numerals-Converter-in-Swift-master/RomanNumeralsMapping/RomanNumeralsMapping/RnmCustomInputTableViewCell.swift:154:42: '++' is deprecated: it will be removed in Swift 3
/Users/ibrahimadnan/Downloads/Roman-numerals-Converter-in-Swift-master/RomanNumeralsMapping/RomanNumeralsMapping/RnmCustomInputTableViewCell.swift:154:9: C-style for statement is deprecated and will be removed in a future version of Swift

**Comment by iadnan** [comment]
Prefix should be capitalized , RnmViewController

**Comment by HussainShabbir** [comment]
Thanks Adnan,

I have updated the code in new Swift style For loops and naming convention. Also have fixed the warning
